I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mod_assets/scripts/scenario/text/ts_scenario_4.rpy", line 1493, in script
    EM "Но,{w=0.2} да - {w}каждую из них убила именно ты." with vpunch
Exception: Sayer 'EM' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/mod_assets/scripts/scenario/text/ts_scenario_4.rpy", line 1493, in script
    EM "Но,{w=0.2} да - {w}каждую из них убила именно ты." with vpunch
  File "D:\renpysource\ts\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\renpysource\ts\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpysource\ts\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'EM' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
True Story 1.0
Sun Feb 25 20:04:00 2024
